name: CI
on:
  push:
    paths-ignore:
      - '**.md'
    branches-ignore:
      - main
  pull_request:
jobs:
  Test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.url != github.event.pull_request.base.repo.url
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shell: [pwsh, powershell]
        exclude:
          - os: ubuntu-latest
            shell: powershell
          - os: macos-latest
            shell: powershell
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Run Pester Tests
        uses: natescherer/pester-tests-report@784ce7ee677a1f66ea92929c323ba6b065c1a9dd # combined
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          shell: ${{ matrix.shell }}
          tests_fail_step: true
          report_name: TestResults_${{ runner.os }}_${{ matrix.shell }}
          coverage_paths: src\private,src\public
          coverage_report_name: CoverageResults_${{ runner.os }}_${{ matrix.shell }}
      #- name: Upload to Codecov
      #  uses: codecov/codecov-action@v3
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
      #    fail_ci_if_error: true
